### ISSUE TITLE
npx rap doesn't work. Wrong package registered inside npx.

### ISSUE THREAD

**Issue by AlithAnar** [rpivo/react-automation-profiler#57]
While trying to call `npx rap` a different app responds.

![image](https://user-images.githubusercontent.com/3205986/134671914-2809ac8c-db32-4c8e-9bcb-17803e23a72f.png)

Are there any plans to revive `rap` package in npx registry (maybe with a different name) ?

How can I run this locally? I'm trying to call:

```
node --experimental-modules ./node_modules/.bin/rap
```

but got 

```
Error: Cannot find package 'fs' imported from /Users/gpasieka/dev/my.livechatinc.com/node_modules/react-automation-profiler/lib/bin.js
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:82:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```

**Comment by rpivo** [comment]
After updates to the `main` branch this week --
If you run `npm run build` in the react-automation-profiler repo, it should create a `lib` folder. If you replace the `lib` folder inside `my.livechatinc.com/node_modules/react-automation-profiler` with this new `lib` folder, do you still get this error?

I'll see if I can reproduce that error locally.

**Comment by rpivo** [comment]
Interesting, that's a good idea. should probably try to make this work with node 12, but I'll add this field for now.
